# SPDX-License-Identifier: Apache-2.0
---

__sap_general_preconfigure_min_pkgs:
  - [ 'setup', '2.12.2-2.el8_1.1' ]

__sap_general_preconfigure_kernel_parameters_default:
  - { name: vm.max_map_count, value: '2147483647' }
  - { name: kernel.pid_max, value: '4194304' }
