# SPDX-License-Identifier: Apache-2.0
---

__sap_general_preconfigure_packages_add_x86_64:
  - compat-sap-c++-9
  - compat-sap-c++-11

__sap_general_preconfigure_packages_add_ppc64le:
  - compat-sap-c++-9
  - compat-sap-c++-11

__sap_general_preconfigure_packages_add_s390x: []

__sap_general_preconfigure_packages: "{{ __sap_general_preconfigure_packages_general +
    lookup('vars', '__sap_general_preconfigure_packages_add_' + ansible_facts['architecture']) }}"
