# SPDX-License-Identifier: Apache-2.0
---

# Corosync post steps
- name: "SAP HA Install Pacemaker - Make sure corosync systemd directory exists"
  ansible.builtin.file:
    path: /etc/systemd/system/corosync.service.d
    state: directory
    mode: '0755'
  when:
    - __sap_ha_pacemaker_cluster_platform == 'cloud_gcp_ce_vm'
  tags: post_ha_cluster

- name: "SAP HA Install Pacemaker - Corosync systemd configuration"
  ansible.builtin.copy:
    backup: true
    content: |-
      [Service]
      ExecStartPre=/bin/sleep 60

    dest: /etc/systemd/system/corosync.service.d/override.conf
    group: root
    owner: root
    mode: '0644'
  when:
    - __sap_ha_pacemaker_cluster_platform == 'cloud_gcp_ce_vm'
  notify: "Reload systemd daemon"
  tags: post_ha_cluster


# HANA
- name: "SAP HA Install Pacemaker - Include srHook configuration"
  ansible.builtin.include_tasks:
    file: post_srhook.yml
    apply:
      tags:
        - srhook
        - post_ha_cluster
  tags:
    - srhook
    - post_ha_cluster
  when:
    - sap_ha_pacemaker_cluster_host_type | select('search', 'hana') | length > 0

# Graceful start of SAPHana clone to ensure resource agents are able to load configuration.
- name: "SAP HA Install Pacemaker - Gracefully start SAP HANA cluster"
  ansible.builtin.include_tasks:
    file: "{{ __task_file }}"
    apply:
      tags: post_ha_cluster
  vars:
    __task_file: "{{ ansible_facts['os_family'] }}/post_hana_scaleup.yml"
    __task_file_path: "{{ role_path }}/tasks/post_tasks/{{ __task_file }}"
  when:
    - __task_file_path is file
    - sap_ha_pacemaker_cluster_host_type | select('search', 'hana_scaleup') | length > 0
  run_once: true
  tags: post_ha_cluster


# ASCS
# Post steps for ASCS/ERS crmsh cluster to remove unsupported operations
- name: "SAP HA Install Pacemaker - Include NetWeaver ASCS/ERS post steps OS specific"
  ansible.builtin.include_tasks:
    file: "{{ __task_file }}"
    apply:
      tags: post_ha_cluster
  vars:
    __task_file: "{{ ansible_facts['os_family'] }}/post_nwas_abap_ascs_ers.yml"
    __task_file_path: "{{ role_path }}/tasks/post_tasks/{{ __task_file }}"
  when:
    - __task_file_path is file
    - sap_ha_pacemaker_cluster_host_type | select('search', 'nwas_abap_ascs_ers') | length > 0
  run_once: true
  tags: post_ha_cluster


# SCS
# Post steps for SCS/ERS crmsh cluster to remove unsupported operations
- name: "SAP HA Install Pacemaker - Include NetWeaver SCS/ERS post steps OS specific"
  ansible.builtin.include_tasks:
    file: "{{ __task_file }}"
    apply:
      tags: post_ha_cluster
  vars:
    __task_file: "{{ ansible_facts['os_family'] }}/post_nwas_java_scs_ers.yml"
    __task_file_path: "{{ role_path }}/tasks/post_tasks/{{ __task_file }}"
  when:
    - __task_file_path is file
    - sap_ha_pacemaker_cluster_host_type | select('search', 'nwas_java_scs_ers') | length > 0
  run_once: true
  tags: post_ha_cluster


# General post-steps
- name: "SAP HA Install Pacemaker - Include NetWeaver ASCS/ERS post steps"
  ansible.builtin.include_tasks:
    file: post_nwas_abap_ascs_ers.yml
    apply:
      tags:
        - nwas_postinst
        - post_ha_cluster
  tags:
    - nwas_postinst
    - post_ha_cluster
  when:
    - sap_ha_pacemaker_cluster_host_type | select('search', 'nwas_abap_ascs_ers') | length > 0

- name: "SAP HA Install Pacemaker - Include NetWeaver SCS/ERS post steps"
  ansible.builtin.include_tasks:
    file: post_nwas_java_scs_ers.yml
    apply:
      tags:
        - nwas_postinst
        - post_ha_cluster
  tags:
    - nwas_postinst
    - post_ha_cluster
  when:
    - sap_ha_pacemaker_cluster_host_type | select('search', 'nwas_java_scs_ers') | length > 0
