# SPDX-License-Identifier: Apache-2.0
---

# The temporary directory holds the sapfile utility, used only by this role.
- name: SAP Install Media Detect - Cleanup - Remove the temporary directory
  ansible.builtin.file:
    path: "{{ __sap_install_media_detect_register_tempfile.path }}"
    state: absent
  when: __sap_install_media_detect_register_tempfile.path is defined
