# SPDX-License-Identifier: Apache-2.0
---

# Internal variables for Ansible Role 'sap_hostagent'.

# Backwards compatibility for deprecated installation type 'sar-remote'.
# This could be removed in a future, if 'sar-remote' installation type is fully deprecated and removed.
__sap_hostagent_installation_type: >-
  {{ 'sar' if sap_hostagent_installation_type == 'sar-remote'
    else sap_hostagent_installation_type }}

__sap_hostagent_sar_remote: >-
  {{ true if sap_hostagent_installation_type == 'sar-remote'
    else sap_hostagent_sar_remote }}


# Boolean status of SAP Host Agent detection, set in 'detect_agent.yml'.
__sap_hostagent_detected: false
