# SPDX-License-Identifier: Apache-2.0
---

# This variable defines the list of hosts to be managed in /etc/hosts.
# Structure definition and examples are available in README.md file.
# It loads variables from other roles, if available, otherwise stays undefined by default.
sap_maintain_etc_hosts_list:
  "{{ sap_hana_cluster_nodes | d(sap_ha_pacemaker_cluster_cluster_nodes) | d([]) }}"

# Delimiter for '/etc/hosts' used to separate all elements on a line.
# Choices: ' ', '\t'
sap_maintain_etc_hosts_delimiter: " "

# Comment to be appended, if comment is not defined in 'sap_maintain_etc_hosts_list'.
sap_maintain_etc_hosts_comment: "managed by Ansible role sap_maintain_etc_hosts"

# Domain name to be used for hosts in 'sap_maintain_etc_hosts_list' if not defined
# or host item does not have 'node_domain' key defined. This is optional and by default it is not set.
# sap_maintain_etc_hosts_domain: ''
