# SPDX-License-Identifier: Apache-2.0
---

### Main Variables

# SAP Storage Setup definition list of dictionary items (List of Dictionaries).
# Each item defines a storage volume for the SAP system.
# Available keys are explained in detail in README.md.
sap_storage_setup_definition: []


### Block Storage Specific Variables

# (Optional) Set to 'true' if the role should enable and detect multipath for SAP storage setup (Boolean).
# NOTE: Installs packages for multipathing, but does not configure actual block devices underneath.
sap_storage_setup_multipath_enable_and_detect: false

# (Optional) Local filesystem type for block storage volumes, if 'filesystem_type' key is not present (String).
sap_storage_setup_local_filesystem_type: xfs


### NFS Mount Specific Variables

# SAP System ID (SID) used to create directories for NFS mounts (String).
sap_storage_setup_sid: ''

# Defines the type of host for the SAP storage setup (List or String).
# Controls what directory name is created under '/usr/sap/<SID>/' path.
# DEV NOTE: Available values are defined in the internal fact '__sap_storage_setup_nfs_dirs_usr_sap'.
sap_storage_setup_host_type: ''

## Instance number for the SAP system instance defined as a two-digit string (String).
# Central Services (ABAP and JAVA)
sap_storage_setup_nwas_abap_ascs_instance_nr: ''    # Type: nwas_abap_ascs -> 'ASCS<nr>'
sap_storage_setup_nwas_java_scs_instance_nr: ''     # Type: nwas_java_scs -> 'SCS<nr>'
sap_storage_setup_nwas_ers_instance_nr: ''          # Type: nwas_ers -> 'ERS<nr>'
# Obsolete ERS types, kept for backward compatibility. NetWeaver has only one ERS for both ABAP and JAVA.
sap_storage_setup_nwas_abap_ers_instance_nr: ''     # Type: nwas_abap_ers -> 'ERS<nr>'
sap_storage_setup_nwas_java_ers_instance_nr: ''     # Type: nwas_java_ers -> 'ERS<nr>'
# NetWeaver ABAP
sap_storage_setup_nwas_abap_pas_instance_nr: ''     # Type: nwas_abap_pas -> 'D<nr>'
sap_storage_setup_nwas_abap_aas_instance_nr: ''     # Type: nwas_abap_aas -> 'D<nr>'
# NetWeaver JAVA
sap_storage_setup_nwas_java_ci_instance_nr: ''      # Type: nwas_java_ci -> 'J<nr>'
# Web Dispatcher
sap_storage_setup_nwas_webdisp_instance_nr: ''      # Type: nwas_webdisp -> 'W<nr>'


# (Optional) NFS server name to use on all NFS mounts, if 'nfs_server' key is not present (String).
# Commented out to use the 'nfs_server' key in individual NFS mount definitions.
# sap_storage_setup_nfs_server: ''

# (Optional) NFS filesystem type to use on all NFS mounts, if 'nfs_filesystem_type' key is not present (String).
sap_storage_setup_nfs_filesystem_type: nfs4

# (Optional) NFS mount options to use on all NFS mounts, if 'nfs_mount_options' key is not present (String).
sap_storage_setup_nfs_mount_options: defaults
