# SPDX-License-Identifier: Apache-2.0
---

# NOTE: This can be replaced completely by 'ansible.builtin.user' module when we increase minimum ansible version to 2.18!
# Argument '-I' is set by module parameter 'password_expire_account_disable' added in 2.18.
# ansible.builtin.user:
#   name: "{{ user_item }}"
#   password_expire_min: 0  # chage -m 0
#   password_expire_max: 99999  # chage -M 99999
#   password_expire_account_disable: -1  # chage -I -1
#   expires: -1  # chage -E -1


- name: SAP SWPM Post Install - Get current chage status for user {{ user_item }}
  ansible.builtin.command:
    cmd: chage -l {{ user_item }}
  register: __sap_swpm_register_post_install_change
  changed_when: false
  become: true

# Reason for noqa: Command 'chage' does not have stdout to check against so we let module decide what is considered change.
- name: SAP SWPM Post Install - Ensure min days is 0 for {{ user_item }}  # noqa no-changed-when
  ansible.builtin.command:
    cmd: chage -m 0 {{ user_item }}
  become: true
  when: not __sap_swpm_register_post_install_change.stdout
    | regex_search('Minimum number of days between password change\\s+:\\s+0')

# Reason for noqa: Command 'chage' does not have stdout to check against so we let module decide what is considered change.
- name: SAP SWPM Post Install - Ensure max days is 99999 for {{ user_item }}  # noqa no-changed-when
  ansible.builtin.command:
    cmd: chage -M 99999 {{ user_item }}
  become: true
  when: not __sap_swpm_register_post_install_change.stdout
    | regex_search('Maximum number of days between password change\\s+:\\s+99999')

# Reason for noqa: Command 'chage' does not have stdout to check against so we let module decide what is considered change.
- name: SAP SWPM Post Install - Ensure password inactive is disabled (-1) for {{ user_item }}  # noqa no-changed-when
  ansible.builtin.command:
    cmd: chage -I -1 {{ user_item }}
  become: true
  when: not __sap_swpm_register_post_install_change.stdout
    | regex_search('Password inactive\\s+:\\s+never')

# Reason for noqa: Command 'chage' does not have stdout to check against so we let module decide what is considered change.
- name: SAP SWPM Post Install - Ensure account expiration is disabled (-1) for {{ user_item }}  # noqa no-changed-when
  ansible.builtin.command:
    cmd: chage -E -1 {{ user_item }}
  become: true
  when: not __sap_swpm_register_post_install_change.stdout
    | regex_search('Account expires\\s+:\\s+never')
