# SPDX-License-Identifier: Apache-2.0
---

__sap_hana_preconfigure_packages:
# SAP NOTE 3562909:
  - tuned-profiles-sap-hana
# package gtk3: only needed if the SAP HANA installation tools hdblcmgui and hdbsetup are used
#  - gtk3
#  - libcanberra-gtk3
#  - PackageKit-gtk3-module
#  - krb5-workstation
  - libatomic
  - libtool-ltdl
  - numactl
#  - xorg-x11-xauth
# package chkconfig: needed by hdblcm to be able to access /etc/init.d
  - chkconfig
  - compat-sap-c++

__sap_hana_preconfigure_packages_min_install:
# SAP NOTE 3562909:
  - tuned-profiles-sap-hana
# package gtk3: only needed if the SAP HANA installation tools hdblcmgui and hdbsetup are used
#  - gtk3
#  - libcanberra-gtk3
#  - PackageKit-gtk3-module
#  - krb5-workstation
  - libatomic
  - libtool-ltdl
  - numactl
#  - xorg-x11-xauth
# package chkconfig: needed by hdblcm to be able to access /etc/init.d
  - chkconfig
  - compat-sap-c++
