# SPDX-License-Identifier: Apache-2.0
---

# This dictionary defines keyword rules to identify SAP binaries compatible with modern Linux distributions supported by SAP HANA.
# Each key is a valid `ansible_facts['architecture']` value.
# The value is a list of rule sets, where each rule set is a list of keywords.
# A file is considered a match if all keywords from any single rule set are found in the `file` command's output.
__sap_swpm_architecture_matrix:
  x86_64:
    # LINUX ON X86_64 64BIT
    # Requires 'ELF' and 'Linux' to differentiate from other x86-64 binaries like those for Solaris (also ELF) or Windows (PE format).
    # Example: SAPCAR_1400-70007716.EXE: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked,
    # interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.4, BuildID[sha1]=52b9652252273d4c212fa366935ea3152244ead4, not stripped
    - ['x86-64', 'ELF', 'Linux']
    # If ELF is UNIX - System V, then check for interpreter linux string.
    - ['x86-64', 'ELF', 'SYSV', 'linux']
  ppc64le:
    # LINUX ON POWER LE 64BIT
    # 'LSB' (Least Significant Bit) is crucial to identify Little-Endian PowerPC, as opposed to the older Big-Endian 'MSB' (Most Significant Bit) variant.
    # Example: SAPCAR_1400-70007726.EXE: ELF 64-bit LSB shared object, 64-bit PowerPC or cisco 7500, OpenPOWER ELF V2 ABI, version 1 (GNU/Linux), dynamically linked,
    # interpreter /lib64/ld64.so.2, for GNU/Linux 3.0.0, BuildID[sha1]=52ce4823a8d2273a2bc15d7c8161a24d65b4223f, not stripped
    - ['PowerPC', 'LSB']
  s390x:
    # LINUX ON ZSERIES 64BIT
    # Identifies binaries for Linux on IBM Z & LinuxONE systems.
    # Example: SAPCAR_1400-70007722.EXE: ELF 64-bit MSB shared object, IBM S/390, version 1 (SYSV), dynamically linked,
    # interpreter /lib/ld64.so.1, for GNU/Linux 2.6.4, BuildID[sha1]=a31118ae8d69bf9422b86930012a6c5776cbc82d, not stripped
    - ['IBM S/390']
  aarch64:
    # LINUX ON ARM 64BIT
    # Identifies binaries for the 64-bit Arm architecture.
    # Example: SAPCAR_1400-80008313.EXE: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (GNU/Linux), dynamically linked,
    # interpreter /lib/ld-linux-aarch64.so.1, BuildID[sha1]=f40042b59e928aacfff753e59686be4d6e242998, for GNU/Linux 3.7.0, not stripped
    - ['aarch64']


# List of firewall packages
__sap_swpm_firewall_packages:
  - firewalld
__sap_swpm_firewall_extra_packages: []

# Predefined firewall service names.
__sap_swpm_firewall_service_name_cs: "sap-nw-central"
__sap_swpm_firewall_service_name_app: "sap-nw-app"


### Internal variables for SAP detection.

# Dictionary Matrix of product prefixes and sections combinations that must be enforced.
# This will ensure that required sections are present for specific products,
# while allowing other products to pass through and potentially fail during SWPM.
# NOTE: Dictionary contains variables that will be expanded only when accessed, which is after validation of inifile!
# - sections - list of sections that must be present in inifile for this product.
# - instances - list of dictionaries with 'number' and 'names' keys to define expected instance number and name format for the instance.
#   - number - unique instance number for the instance.
#   - names - list of possible instance names for the instance. Any of them means that the instance is detected.
__sap_swpm_product_sections_dict:
  # Product Catalog ID prefix.
  # Example: 'NW_ABAP_ASCS' for product catalog ID 'NW_ABAP_ASCS:S4HANA2025.CORE.HDB.ABAP'.
  # Contains: ASCS
  NW_ABAP_ASCS:
    # Name of section in 'sap_swpm_inifile_sections_list' that must be present for this product.
    sections:
      - nw_config_central_services_abap
    instances:
      - number: "{{ sap_swpm_ascs_instance_nr }}"
        names:
          - "{{ 'ASCS' ~ sap_swpm_ascs_instance_nr }}"

  # Contains: SCS
  NW_Java_SCS:
    sections:
      - nw_config_central_services_java
    instances:
      - number: "{{ sap_swpm_java_scs_instance_nr }}"
        names:
          - "{{ 'SCS' ~ sap_swpm_java_scs_instance_nr }}"

  # Contains: ERS
  NW_ERS:
    sections:
      - nw_config_ers
    instances:
      - number: "{{ sap_swpm_ers_instance_nr }}"
        names:
          - "{{ 'ERS' ~ sap_swpm_ers_instance_nr }}"

  # Contains: ASCS, PAS (ABAP)
  # DVEBMGS is used as fallback to legacy instance name.
  NW_ABAP_OneHost:
    sections:
      - nw_config_central_services_abap
      - nw_config_primary_application_server_instance
    instances:
      - number: "{{ sap_swpm_ascs_instance_nr }}"
        names:
          - "{{ 'ASCS' ~ sap_swpm_ascs_instance_nr }}"
      - number: "{{ sap_swpm_pas_instance_nr }}"
        names:
          - "{{ 'D' ~ sap_swpm_pas_instance_nr }}"
          - "{{ 'DVEBMGS' ~ sap_swpm_pas_instance_nr }}"

  # Contains: PAS
  NW_ABAP_CI:
    sections:
      - nw_config_primary_application_server_instance
    instances:
      - number: "{{ sap_swpm_pas_instance_nr }}"
        names:
          - "{{ 'DVEBMGS' ~ sap_swpm_pas_instance_nr }}"
          - "{{ 'D' ~ sap_swpm_pas_instance_nr }}"

  # Contains: ASCS, PAS (JAVA)
  NW_Java_CI:
    sections:
      - nw_config_primary_application_server_instance
    instances:
      - number: "{{ sap_swpm_pas_instance_nr }}"
        names:
          - "{{ 'J' ~ sap_swpm_pas_instance_nr }}"

  # Contains: AAS (ABAP or JAVA)
  NW_DI:
    sections:
      - nw_config_additional_application_server_instance
    instances:
      - number: "{{ sap_swpm_aas_instance_nr }}"
        names:
          - "{{ 'D' ~ sap_swpm_aas_instance_nr }}"
          - "{{ 'J' ~ sap_swpm_aas_instance_nr }}"


# This is special list of product prefixes, where we cannot detect SAP,
# because it does not create any recognizable files.
# NOTE: Do not add product prefixes already in '__sap_swpm_product_sections_dict'!
__sap_swpm_product_detection_unavailable:
  # List of product prefixes that cannot be allowed to proceed without explicit acknowledgement.
  fail: []

  # List of safe product prefixes that can be allowed to proceed without explicit acknowledgement.
  skip: []

  # Dedicated fail list for Database Load products, which are considered unsafe to proceed without explicit acknowledgement.
  # Database load installs only 'saphostctrl' and rest is done in database.
  # This is not conclusive enough for us to decide and SWPM handles this itself.
  dbload:
    - NW_ABAP_DB
    - NW_Java_DB

# System ID (SID) in upper case.
__sap_swpm_sid: "{{ sap_swpm_sid | upper }}"

# Name of '<sid>adm' user.
__sap_swpm_sidadm_user: "{{ sap_swpm_sid | lower }}adm"
