# SPDX-License-Identifier: Apache-2.0
---

# Internal variables for sap_maintain_etc_hosts role

# Path to the /etc/hosts file.
__sap_maintain_etc_hosts_file: /etc/hosts

# Regex patterns for IP address validation.
__sap_maintain_etc_hosts_regexp_ipv4:
  '^((25[0-5]|(2[0-4]|1\d|[1-9]|)\d)\.?\b){4}$'
__sap_maintain_etc_hosts_regexp_ipv6:
  '^(?:(?:[0-9a-fA-F]{1,4}:){7}[0-9a-fA-F]{1,4}|(?:[0-9a-fA-F]{1,4}:){1,7}:|(?:[0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|(?:[0-9a-fA-F]{1,4}:){1,5}(?::[0-9a-fA-F]{1,4}){1,2}|(?:[0-9a-fA-F]{1,4}:){1,4}(?::[0-9a-fA-F]{1,4}){1,3}|(?:[0-9a-fA-F]{1,4}:){1,3}(?::[0-9a-fA-F]{1,4}){1,4}|(?:[0-9a-fA-F]{1,4}:){1,2}(?::[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:(?::[0-9a-fA-F]{1,4}){1,6}|:(?::[0-9a-fA-F]{1,4}){1,7}|::)$'
