# SPDX-License-Identifier: Apache-2.0
---

- name: SAP Host Agent - Bundle - Extract the SAP Host Agent file from the Bundle
  ansible.builtin.unarchive:
    src: "{{ __sap_hostagent_fact_bundle_path }}"
    dest: "{{ __sap_hostagent_register_tmpdir.path }}"
    remote_src: true
    mode: '0755'


# Default path in SAP HANA archive is 'global/hdb/saphostagent_setup/saphostexec'.
- name: SAP Host Agent - Bundle - Set fact with full path to saphostexec file directory in extracted HOSTAGENT.TGZ file
  ansible.builtin.set_fact:
    __sap_hostagent_fact_saphostexec_dir_path:
      "{{ __sap_hostagent_register_tmpdir.path }}/global/hdb/saphostagent_setup"

- name: SAP Host Agent - Bundle - Stat saphostexec in extracted HOSTAGENT.TGZ file
  ansible.builtin.stat:
    path: "{{ __sap_hostagent_fact_saphostexec_dir_path }}"
  register: __sap_hostagent_register_saphostexec_stat

- name: SAP Host Agent - Bundle - Fail if the saphostexec file does not exist
  ansible.builtin.fail:
    msg: |
      FAIL: The SAP Host Agent executable '{{ __sap_hostagent_fact_saphostexec_dir_path }}/saphostexec' was not found in the extracted archive.
      Ensure that the '{{ __sap_hostagent_fact_bundle_path }}' is valid SAP archive.
  when: not __sap_hostagent_register_saphostexec_stat.stat.exists


# Output contains typo so we need to use regex: [OK] SAPHostExec / SAPHostControl successfully installed
# RC=0 is valid, but it outputs into 'stderr' instead of 'stdout', so we need to check both.
- name: SAP Host Agent - Bundle - Install SAP Host Agent using saphostexec
  ansible.builtin.command:
    cmd: >-
      {{ __sap_hostagent_fact_saphostexec_dir_path }}/saphostexec -install
  args:
    chdir: "{{ __sap_hostagent_fact_saphostexec_dir_path }}/"
  become: true
  become_user: root
  register: __sap_hostagent_register_install_bundle
  changed_when: >-
    __sap_hostagent_register_install_bundle.stdout is search('SAPHostExec.*installed')
    or 'Start saphostagent.service' in __sap_hostagent_register_install_bundle.stdout
    or __sap_hostagent_register_install_bundle.stderr is search('SAPHostExec.*installed')
    or 'Start saphostagent.service' in __sap_hostagent_register_install_bundle.stderr
