# SPDX-License-Identifier: Apache-2.0
---
# Set log_mode at SYSTEM layer only. HOST layer overrides are not managed by this role.

- name: SAP HSR - Check current log_mode in SYSTEM global.ini
  become: true
  become_user: "{{ __sap_ha_install_hana_hsr_sid | lower }}adm"
  ansible.builtin.shell:
    cmd: |
      /usr/sap/{{ __sap_ha_install_hana_hsr_sid }}/SYS/exe/hdb/hdbsql \
      -U {{ sap_ha_install_hana_hsr_hdbuserstore_system_backup_user }} \
      -m <<EOF
      SELECT VALUE FROM M_INIFILE_CONTENTS
        WHERE FILE_NAME = 'global.ini'
        AND LAYER_NAME = 'SYSTEM'
        AND SECTION = 'persistence'
        AND KEY = 'log_mode'
        AND VALUE = 'normal';
      EOF
  register: __sap_ha_install_hana_hsr_register_log_mode
  failed_when: false
  changed_when: false

# This task will fail when HSR is already configured,
# because secondary node nameserver is not running with port 3XX13.
- name: SAP HSR - Set log_mode to normal for SYSTEM
  become: true
  become_user: "{{ __sap_ha_install_hana_hsr_sid | lower }}adm"
  ansible.builtin.shell:
    cmd: |
      /usr/sap/{{ __sap_ha_install_hana_hsr_sid }}/SYS/exe/hdb/hdbsql \
      -U {{ sap_ha_install_hana_hsr_hdbuserstore_system_backup_user }} \
      -m <<EOF
      ALTER SYSTEM ALTER CONFIGURATION('global.ini','SYSTEM')
        SET ('persistence','log_mode')
        = 'normal' WITH RECONFIGURE;
      EOF
  ignore_errors: true
  when: "'normal' not in __sap_ha_install_hana_hsr_register_log_mode.stdout"
  changed_when: true
