# SPDX-License-Identifier: Apache-2.0
---

# Subset can be enhanced to ipv6 in future using 'sap_maintain_etc_hosts_gather_subset' variable.
# This is used only for undefined 'sap_maintain_etc_hosts_list' variable.
- name: SAP Maintain Hosts - Ensure required defaults are read from setup module
  ansible.builtin.setup:
    gather_subset:
      - 'default_ipv4'
    filter:
      - "ansible_facts['hostname']"
      - "ansible_facts['domain']"
      - "ansible_facts['default_ipv4']"

# Get contents of hosts file as slurp and transform it into facts.
- name: SAP Maintain Hosts - Gather contents of hosts file
  ansible.builtin.include_tasks:
    file: get_hosts_file.yml

# Go through variable and assert that structure is correct,
# but also validate against existing hosts file.
- name: SAP Maintain Hosts - Validate contents of the 'sap_maintain_etc_hosts_list' variable
  ansible.builtin.include_tasks:
    file: validate_variables.yml
  when:
    - sap_maintain_etc_hosts_list | d([]) | length > 0
    - sap_maintain_etc_hosts_list | type_debug == 'list'

# Convert input list into final format for looping in validation and state tasks.
- name: SAP Maintain Hosts - Prepare final list of lines to update in hosts file
  ansible.builtin.include_tasks:
    file: prepare_variables.yml


- name: SAP Maintain Hosts - Maintain entries in hosts file
  ansible.builtin.include_tasks:
    file: state_{{ __sap_maintain_etc_hosts_item.state | d('present') }}.yml
  loop: "{{ __sap_maintain_etc_hosts_fact_hosts_list }}"
  loop_control:
    label: "{{ __sap_maintain_etc_hosts_item.node_name | d(__sap_maintain_etc_hosts_item.node_ip) | d('N/A') }}"
    loop_var: __sap_maintain_etc_hosts_item
