# SPDX-License-Identifier: Apache-2.0
---

- name: SAP HA Install Pacemaker - Firewall - Install packages
  ansible.builtin.package:
    name: "{{ __sap_ha_pacemaker_cluster_firewall_packages + __sap_ha_pacemaker_cluster_firewall_extra_packages }}"
    state: present

- name: SAP HA Install Pacemaker - Firewall - Start and enable firewalld service
  ansible.builtin.systemd_service:
    name: firewalld
    state: started
    enabled: true
    masked: false


# Validate firewall zone if defined
- name: Block for validation of firewall zone
  when: sap_ha_pacemaker_cluster_firewall_zone is defined
  block:
    - name: SAP HA Install Pacemaker - Firewall - Get list of configured zones from firewalld
      ansible.builtin.command:
        cmd: firewall-cmd --get-zones
      register: __sap_ha_pacemaker_cluster_register_firewall_zones
      changed_when: false

    - name: SAP HA Install Pacemaker - Firewall - Assert that the firewall zone is available
      ansible.builtin.assert:
        that:
          - sap_ha_pacemaker_cluster_firewall_zone in __sap_ha_pacemaker_cluster_register_firewall_zones.stdout.split()
        success_msg: |
          PASS: The zone '{{ sap_ha_pacemaker_cluster_firewall_zone }}' is present in firewalld.
        fail_msg: |
          FAIL: The zone '{{ sap_ha_pacemaker_cluster_firewall_zone }}' is not preset in firewalld.
          Available zones: {{ __sap_ha_pacemaker_cluster_register_firewall_zones.stdout }}
        quiet: true


# Proceed straight to firewall service configuration as custom ports are not an option.
- name: SAP HA Install Pacemaker - Firewall - Generate service file from template
  ansible.builtin.template:
    src: firewall-ha-cluster.j2
    dest: "/etc/firewalld/services/{{ __sap_ha_pacemaker_cluster_firewall_service_name }}.xml"
    owner: 'root'
    group: 'root'
    mode: '0640'

- name: SAP HA Install Pacemaker - Firewall - Reload firewalld after creating service file
  ansible.builtin.command:
    cmd: firewall-cmd --reload
  changed_when: true

- name: SAP HA Install Pacemaker - Firewall - Configure service in firewall
  ansible.builtin.command:
    cmd: >-
      firewall-cmd
      {% if sap_ha_pacemaker_cluster_firewall_zone is defined %}
      --zone={{ sap_ha_pacemaker_cluster_firewall_zone }}
      {% endif %}
      --permanent
      --add-service={{ __sap_ha_pacemaker_cluster_firewall_service_name }}
  register: __sap_ha_pacemaker_cluster_register_firewall_add_service
  changed_when: true


- name: SAP HA Install Pacemaker - Firewall - Reload firewalld after applying changes
  ansible.builtin.command:
    cmd: firewall-cmd --reload
  changed_when: true

- name: SAP HA Install Pacemaker - Firewall - Get current firewall configuration of the default zone
  ansible.builtin.command:
    cmd: firewall-cmd --list-all
  changed_when: false
  register: __sap_ha_pacemaker_cluster_register_current_firewall_configuration


- name: SAP HA Install Pacemaker - Firewall - Show details of configured firewall
  ansible.builtin.debug:
    msg: |
      Firewall was configured for SAP High Availability Cluster and reloaded.
      Output of command 'firewall-cmd --list-all':
      {{ __sap_ha_pacemaker_cluster_register_current_firewall_configuration.stdout }}
  when: __sap_ha_pacemaker_cluster_register_current_firewall_configuration.stdout is defined
