# SPDX-License-Identifier: Apache-2.0
---

# Red Hat specific variables.

__sap_storage_setup_packages:
  - lvm2
  - nfs-utils
  # - lvm2-dbusd

# __sap_storage_setup_services:
#  - lvm2-lvmdbusd


# Multipath specific variables.
__sap_storage_setup_packages_multipath:
  - device-mapper-multipath

__sap_storage_setup_services_multipath:
  - multipathd
