# SPDX-License-Identifier: Apache-2.0
---

# SUSE specific variables

__sap_storage_setup_packages:
  - lvm2
  - nfs-client

# __sap_storage_setup_services:
#  - lvm2-lvmdbusd


# Multipath specific variables.
__sap_storage_setup_packages_multipath:
  - multipath-tools

__sap_storage_setup_services_multipath:
  - multipathd
