# SPDX-License-Identifier: Apache-2.0
---

# Fail when more than one tag is used
- name: SAP HANA - Main - Fail if more than one tag is used
  ansible.builtin.fail:
    msg: "This role supports only one tag at a time."
  when: ansible_run_tags | d([]) | count > 1
  tags: always

# Example of files loading order:
# 1. Suse.yml / RedHat.yml - Specific to OS family.
# 2. SLES_15.yml / RedHat_9.yml - Specific to distribution (SLES, SLES_SAP or RedHat) and major release.
# 3. SLES_15.6.yml / RedHat_9.2 - Specific to distribution (SLES, SLES_SAP or RedHat) and minor release.
# 4. SLES_SAP_15.yml - Specific to distribution SLES_SAP and major release.
# 5. SLES_SAP_15.6.yml - Specific to distribution SLES_SAP and minor release.
- name: SAP Firewall - Include OS specific vars
  ansible.builtin.include_vars: "{{ __vars_file }}"
  loop: "{{ __var_files }}"
  vars:
    __vars_file: "{{ role_path }}/vars/{{ item }}"
    __distribution_major: "{{ ansible_facts['distribution'] ~ '_' ~ ansible_facts['distribution_major_version'] }}"
    __distribution_minor: "{{ ansible_facts['distribution'] ~ '_' ~ ansible_facts['distribution_version'] }}"
    # Enables loading of shared vars between SLES and SLES_SAP
    __distribution_major_split: "{{ ansible_facts['distribution'].split('_')[0] ~ '_' ~ ansible_facts['distribution_major_version'] }}"
    __distribution_minor_split: "{{ ansible_facts['distribution'].split('_')[0] ~ '_' ~ ansible_facts['distribution_version'] }}"
    __var_files: >-
      {{
        [
          ansible_facts['os_family'] ~ '.yml',
          (ansible_facts['distribution'] ~ '.yml') if ansible_facts['distribution'] != ansible_facts['os_family'] else None,
          (__distribution_major_split ~ '.yml') if __distribution_major_split != __distribution_major else None,
          (__distribution_minor_split ~ '.yml') if __distribution_minor_split != __distribution_minor else None,
          __distribution_major ~ '.yml',
          __distribution_minor ~ '.yml'
        ] | select('defined') | select('string') | list
      }}
  when: __vars_file is file
  tags: always

- name: SAP HANA - Main - Prepare some variables
  ansible.builtin.include_tasks:
    file: pre_tasks/prepare_variables.yml
    apply:
      tags: always
  tags: always


# Process all hosts in play and define flag facts based on their intended role during installation.
# - Detect Scale-Out and Addhosts operations.
# - Set host identification flags
# - Validate addhosts list against hosts in the play.
- name: SAP HANA - Main - Identify hosts in play
  ansible.builtin.include_tasks:
    file: pre_tasks/identify_hosts.yml


# SAP HANA presence has to be validated for both new system and adding new hosts.
# - Detection is executed even in force mode, but fails are skipped to allow execution of the role.
# - Host identification flags are used to ignore /hana/shared file detection check for Scale-Out addhosts hosts.
- name: SAP HANA - Main - Validate presence of existing SAP HANA database
  ansible.builtin.include_tasks:
    file: pre_tasks/detect_hana.yml
    apply:
      tags:
        - sap_hana_install_check_hana_exists
  tags:
    - sap_hana_install_check_hana_exists


# Validate detected SAP installations against allowed Scale-Out scenarios.
- name: SAP HANA - Main - Validate hosts in play
  ansible.builtin.include_tasks:
    file: pre_tasks/validate_hosts.yml
  when: __sap_hana_install_fact_is_scaleout


- name: SAP HANA - Main - Ensure SAP HANA is running for existing systems or addhosts operations
  ansible.builtin.include_tasks:
    file: pre_tasks/hana_start.yml
  when:
    - __sap_hana_install_fact_is_installed
    - __sap_hana_install_fact_is_main_host


# Instructions for separating tasks to achieve idempotency:
# - Installation - Run once for new installations, never repeated.
# - Configuration - Run always to ensure idempotent outcome.

- name: Block for Installation tasks
  # Stop execution of remaining tasks in the role, if any task in the block failed on any host.
  # This ensures that the role does not proceed skipping failed host, but fails the entire role execution.
  # 'any_errors_fatal' is not documented to work on task level, therefore we use simple block.
  # http://docs.ansible.com/projects/ansible/latest/playbook_guide/playbooks_error_handling.html#aborting-on-the-first-error-any-errors-fatal
  # Runs on all hosts in Scale-Out scenario, but allows independent failures for single host installations.
  any_errors_fatal: "{{ true if __sap_hana_install_fact_is_scaleout else false }}"
  when:
    - sap_hana_install_new_system
      or (ansible_run_tags | d([])
        | intersect(['sap_hana_install_create_configfile', 'sap_hana_install_hdblcm_commandline'])) | length > 0
  block:
    # Task file contains pseudo-idempotency checks and cannot be skipped for installed system.
    - name: SAP HANA - Install - Pre-Tasks
      ansible.builtin.include_tasks:
        file: pre_install.yml
      tags:
        - sap_hana_install_create_configfile
        - sap_hana_install_hdblcm_commandline

    - name: SAP HANA - Install
      ansible.builtin.include_tasks:
        file: hana_install.yml
      when:
        - (not __sap_hana_install_fact_is_installed and __sap_hana_install_fact_is_main_host)
          or (ansible_run_tags | d([]) | intersect(['sap_hana_install_hdblcm_commandline'])) | length > 0
      tags: sap_hana_install_hdblcm_commandline

    - name: SAP HANA - Install - Post-tasks
      ansible.builtin.include_tasks:
        file: post_install.yml


- name: Block for Addhosts tasks
  # Stop execution of remaining tasks in the role, if any task in the block failed on any host.
  # This ensures that the role does not proceed skipping failed host, but fails the entire role execution.
  # 'any_errors_fatal' is not documented to work on task level, therefore we use simple block.
  # http://docs.ansible.com/projects/ansible/latest/playbook_guide/playbooks_error_handling.html#aborting-on-the-first-error-any-errors-fatal
  # Runs on all hosts in addhosts scenario.
  any_errors_fatal: true
  when:
    - not sap_hana_install_new_system
      and (__sap_hana_install_fact_is_scaleout
        or (ansible_run_tags | d([])
          | intersect(['sap_hana_install_create_configfile', 'sap_hana_install_hdblcm_commandline'])) | length > 0)
  block:
    # Execute only if new hosts are to be added.
    - name: SAP HANA - Addhosts - Pre-Tasks
      ansible.builtin.include_tasks:
        file: pre_addhosts.yml
      when:
        - __sap_hana_install_fact_addhosts_hosts_new | d([]) | length > 0
          or (ansible_run_tags | d([])
            | intersect(['sap_hana_install_create_configfile', 'sap_hana_install_hdblcm_commandline'])) | length > 0
      tags:
        - sap_hana_install_hdblcm_commandline
        - sap_hana_install_create_configfile

    - name: SAP HANA - Addhosts
      ansible.builtin.include_tasks:
        file: hana_addhosts.yml
      when:
        - (__sap_hana_install_fact_addhosts_hosts_new | d([]) | length > 0 and __sap_hana_install_fact_is_main_host)
          or (ansible_run_tags | d([])
            | intersect(['sap_hana_install_create_configfile', 'sap_hana_install_hdblcm_commandline'])) | length > 0
      tags:
        - sap_hana_install_hdblcm_commandline
        - sap_hana_install_create_configfile

    - name: SAP HANA - Addhosts - Post-tasks
      ansible.builtin.include_tasks:
        file: post_addhosts.yml


# Show final status of SAP HANA System
# Gather details about installed database for finished message
- name: SAP HANA - Main - Run 'hdblcm --list_systems' after the completion
  ansible.builtin.shell: |
      set -o pipefail && ./hdblcm --list_systems | awk '/\/hana\/shared\/{{ sap_hana_install_sid }}/{a=1}
      /version:/{if (a==1){
        gsub ("^\\s*version: ", "");printf ("%s;", $NF)}
      }
      /hosts?:/{if (a==1){
        gsub ("^\\s*hosts?: ", ""); gsub (", ", ","); print; a=0}
      }'
  args:
    chdir: "{{ __sap_hana_install_shared_path }}/hdblcm"
  register: __sap_hana_install_register_completion_result
  changed_when: false
  when:
    - not ansible_check_mode
    - __sap_hana_install_fact_is_main_host

- name: SAP HANA - Main - Display SAP HANA details and completed post tasks
  ansible.builtin.debug:
    msg: |
      SAP HANA database is installed and running:
      HANA Version     -       {{ __sap_hana_install_fact_hana_version }}
      Hosts            -       {{ __sap_hana_install_fact_hana_hosts }}
      SID              -       {{ sap_hana_install_sid }}
      NR               -       {{ sap_hana_install_number }}

      {% if sap_hana_install_configure_firewall %}
      Firewall is enabled and SAP HANA ports are open.
      {% endif %}
      {% if __sap_hana_install_configure_selinux %}
      SELinux file contexts are configured for SAP folders ({{ sap_hana_install_directories | map('quote') | join(', ') }}).
      {% endif %}
      {% if ansible_facts['os_family'] == "RedHat" and __sap_hana_install_configure_fapolicyd %}
      Fapolicyd is configured for SAP folders ({{ sap_hana_install_directories | map('quote') | join(', ') }}).
      {% endif %}
  vars:
    __sap_hana_install_fact_hana_version: "{{ __sap_hana_install_register_completion_result.stdout.split(';')[0] | d('N/A') }}"
    __sap_hana_install_fact_hana_hosts: "{{ __sap_hana_install_register_completion_result.stdout.split(';')[1] | d('N/A') }}"
  when:
    - not ansible_check_mode
    - __sap_hana_install_fact_is_main_host
