# SPDX-License-Identifier: Apache-2.0
---

### Detection and Validation of included variables
# Validation of user vars and included vars for detected platform and OS.
- name: "SAP HA Prepare Pacemaker - Include detection and variable inclusion tasks"
  ansible.builtin.import_tasks:
    file: include_vars/include_main.yml
  tags: always

### Prepare variables based on cluster type, platform and OS.
# Tasks will generate variables in format to be accepted by 'ha_cluster' role.
- name: "SAP HA Prepare Pacemaker - Include variable preparation tasks"
  ansible.builtin.import_tasks:
    file: prepare_vars/prepare_main.yml
  tags: pre_ha_cluster

### Pre-Tasks before configuring cluster
# Following tasks will execute actual changes on the target systems
# Cluster type, platform and OS specific pre-tasks.
- name: "SAP HA Prepare Pacemaker - Include pre-tasks"
  ansible.builtin.include_tasks:
    file: pre_tasks/pre_main.yml
    apply:
      tags: pre_ha_cluster
  tags: pre_ha_cluster

### Execution of 'linux_system_roles.ha_cluster' role.
- name: "SAP HA Install Pacemaker - Include Ansible Role 'ha_cluster'"
  ansible.builtin.include_role:
    name: "{{ sap_ha_pacemaker_cluster_system_roles_collection }}.ha_cluster"
    apply:
      tags: run_ha_cluster
      ignore_errors: "{{ ansible_check_mode }}"
  no_log: "{{ __sap_ha_pacemaker_cluster_no_log }}"  # some parameters contain secrets
  tags: run_ha_cluster

### Post-Tasks before configuring cluster
# Cluster type, platform and OS specific post-tasks.
- name: "SAP HA Prepare Pacemaker - Include post-tasks"
  ansible.builtin.include_tasks:
    file: post_tasks/post_main.yml
    apply:
      tags:
        - srhook
        - post_ha_cluster
  tags:
    - srhook
    - post_ha_cluster
