# SPDX-License-Identifier: Apache-2.0
---

# Assert certain vars
#
- name: SAP SWPM Prepare - Check availability of 'sap_swpm_software_path'
  ansible.builtin.stat:
    path: "{{ sap_swpm_software_path }}"
  register: __sap_swpm_register_software_path
  when: sap_swpm_software_path is defined and sap_swpm_software_path | length > 0

- name: SAP SWPM - Assert that 'sap_swpm_software_path' is defined and a valid directory
  ansible.builtin.assert:
    that:
      - sap_swpm_software_path is defined
      - sap_swpm_software_path is string
      - sap_swpm_software_path | trim | length > 0
      - __sap_swpm_register_software_path.stat.exists
      - __sap_swpm_register_software_path.stat.isdir
    fail_msg: "FAIL: The variable 'sap_swpm_software_path' does not specify an existing directory!"
    success_msg: "PASS: The variable 'sap_swpm_software_path' is defined as an existing directory, with a value of: '{{ sap_swpm_software_path }}'."

- name: SAP SWPM - Set internal software_path variable
  ansible.builtin.set_fact:
    __sap_swpm_fact_software_path: "{{ sap_swpm_software_path }}"


# Rename certain variables while maintaining backwards compatibility
#
- name: SAP SWPM - Rename sap_swpm_swpm variables if found
  ansible.builtin.set_fact:
    __sap_swpm_fact_sapcar_path:
      "{{ sap_swpm_sapcar_path
          if (sap_swpm_sapcar_path is defined and sap_swpm_sapcar_path | trim | length > 0)
          else __sap_swpm_fact_software_path }}"
    __sap_swpm_fact_swpm_path:
      "{{ sap_swpm_path
          if (sap_swpm_path is defined and sap_swpm_path | trim | length > 0)
          else (sap_swpm_swpm_path
            if (sap_swpm_swpm_path is defined and sap_swpm_swpm_path | trim | length > 0)
            else __sap_swpm_fact_software_path) }}"
    __sap_swpm_fact_swpm_file_name:
      "{{ sap_swpm_file_name
          if (sap_swpm_file_name is defined and sap_swpm_file_name | trim | length > 0)
          else (sap_swpm_swpm_sar_file_name
            if (sap_swpm_swpm_sar_file_name is defined and sap_swpm_swpm_sar_file_name | trim | length > 0)
            else '') }}"
    __sap_swpm_fact_observer_mode:
      "{{ (sap_swpm_observer_mode if sap_swpm_observer_mode is defined
           else sap_swpm_swpm_observer_mode | default(false)) | bool }}"
    __sap_swpm_fact_remote_access_user:
      "{{ sap_swpm_remote_access_user
          if (sap_swpm_remote_access_user is defined and sap_swpm_remote_access_user | trim | length > 0)
          else (sap_swpm_swpm_remote_access_user
            if (sap_swpm_swpm_remote_access_user is defined and sap_swpm_swpm_remote_access_user | trim | length > 0)
            else '') }}"
